server:
  port: 8080

spring:
  datasource:
    username: /*user*/
    password: /*password*/
    url: jdbc:mysql://localhost:3306/searchDB?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true&useUnicode=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
indexing-settings:
  sites:
    - url: https://dombulgakova.ru
      name: dombulgakova.ru
    - url: https://megaline.kg
      name: megaline.kg
    - url: https://araparbi.kg
      name: araparbi.kg
    - url: https://volochek.life
      name: volochek.life


